### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexBuilderForDebug' after upgrading Android Gradle Plugin to 3.5.x

### ISSUE THREAD

**Issue by salockhart** [react-native-community/upgrade-support#108]
## Environment

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 181.19 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/alockha/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0.1 4.0.1
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Upgrading version

0.63.2

## Description

After upgrading my Android Gradle Plugin from 3.4.3 to 3.5.3, I am getting an issue in the `:app:transformClassesWithDexBuilderForDebug` task. The same happens if I try to upgrade to 3.6.x or 4.0.x.

```
	Suppressed: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
		at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
		at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:513)
		at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:82)
		at com.android.tools.r8.utils.ThreadUtils.a(:4)
		at com.android.tools.r8.ir.conversion.IRConverter.a(:46)
		... 43 more
	[CIRCULAR REFERENCE:java.lang.UnsupportedOperationException]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> There were multiple failures while executing work items
   > A failure occurred while executing com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$DexConversionWorkAction
      > Failed to process /Users/alockha/Projects/mobile/App/android/app/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$DexConversionWorkAction
      > Failed to process /Users/alockha/Projects/mobile/App/android/app/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$DexConversionWorkAction
      > Failed to process /Users/alockha/Projects/mobile/App/android/app/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$DexConversionWorkAction
      > Failed to process /Users/alockha/Projects/mobile/App/android/app/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$DexConversionWorkAction
      > Failed to process /Users/alockha/Projects/mobile/App/android/app/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$DexConversionWorkAction
      > Failed to process /Users/alockha/Projects/mobile/App/android/app/build/intermediates/javac/debug/classes
```

## Reproducible demo

I've created a vanilla RN app and it doesn't have this issue, although I've compared the gradle settings in both and there doesn't appear to be any aggregious differences. I'm not sure I am able to provide a reproducible demo

**Comment by vgvishal538** [comment]
Did anyone found any solution for this issue?
