### ISSUE TITLE
After upgrade to 0.64, build fails with "Unexpected token: name (_000) in file App.tsx at 22:23."

### ISSUE THREAD

**Issue by devinjameson** [react-native-community/upgrade-support#142]
## Environment
```
  OS: macOS 11.2.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Memory: 793.96 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 15.12.0 - ~/.asdf/installs/nodejs/15.12.0/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 7.6.3 - ~/.asdf/installs/nodejs/15.12.0/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
  CocoaPods: 1.10.1 - /Users/devinjameson/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  Android SDK: Not Found
IDEs:
  Android Studio: 4.0 AI-193.6911.18.40.6626763
  Xcode: 12.4/12D4e - /usr/bin/xcodebuild
Languages:
  Java: 13.0.1 - /usr/bin/javac
  Python: 2.7.16 - /usr/bin/python
npmPackages:
  @react-native-community/cli: Not Found
  react: 17.0.1 => 17.0.1 
  react-native: 0.64.0 => 0.64.0 
  react-native-macos: Not Found
npmGlobalPackages:
  *react-native*: Not Found
```

## Things I’ve done to figure out my issue

- [√] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.
- Looked here for similar issues

## Upgrading version

`0.63.4` to `0.64`

## Description

Builds are failing after upgrade.

Command: `xcodebuild -workspace ios/MyApp.xcworkspace -scheme MyApp -configuration Release -sdk iphonesimulator -derivedDataPath ios/build`

Here's the output:

```
error App.tsx: Unexpected token: name (_000) in file App.tsx at 22:23.                      
Error: Unexpected token: name (_000) in file App.tsx at 22:23                               
    at /Users/devinjameson/Documents/repos/MyApp/node_modules/metro-transform-worker/src/index.js:279:15                                                                   
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/devinjameson/Documents/repos/MyApp/node_modules/metro-transform-worker/src/index.js:146:24)                                              
    at _next (/Users/devinjameson/Documents/repos/MyApp/node_modules/metro-transform-worker/src/index.js:168:9)                                                            
    at /Users/devinjameson/Documents/repos/MyApp/node_modules/metro-transform-worker/src/index.js:175:7                                                                    
    at new Promise (<anonymous>) 
    at /Users/devinjameson/Documents/repos/MyApp/node_modules/metro-transform-worker/src/index.js:164:12                                                                   
    at minifyCode (/Users/devinjameson/Documents/repos/MyApp/node_modules/metro-transform-worker/src/index.js:289:17)                                                      
    at Object.<anonymous> (/Users/devinjameson/Documents/repos/MyApp/node_modules/metro-transform-worker/src/index.js:569:40)                                             
info Run CLI with --verbose flag for more details.
Command PhaseScriptExecution failed with a nonzero exit code
```
```
** BUILD FAILED **
The following build commands failed:
        PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/devinjameson/Documents/repos/MyApp/ios/build/Build/Intermediates.noindex/MyApp.b
uild/Release-iphonesimulator/MyApp.build/Script-00DD1BFF1BD5951E006B06BC.sh
```

## Reproducible demo

Upgrade to React Native 0.64. Try to build your app. Maybe it will fail and produce this issue?

**Comment by devinjameson** [comment]
Eventually tracked it down to a non-upgrade-related issue.
