### ISSUE TITLE
How to create native library

### ISSUE THREAD

**Issue by dbasilioesp** [react-native-community/upgrade-support#16]
## Upgrading version

0.62.0

## Description

Creating react native library throw error with RNGADBannerView

Hi, I trying to create a simple library module following the instructions in https://reactnative.dev/docs/native-modules-setup .
After create the library and the example inside using `react-native init ExampleNative`, added the library to package.json of Example app.

**Log**

```
info Reloading app...
[Fri Mar 27 2020 15:20:46.830]  BUNDLE  ./index.js

error: Error: Unable to resolve module `./RNGADBannerView` from `node_modules\react-native-my-library\index.js`:

None of these files exist:
  * node_modules\react-native-my-library\RNGADBannerView(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-my-library\RNGADBannerView\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\lindi\workspace\plugins\react-native-my-library\ExampleNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
```

**react-native-my-library/index.js**

```
import { NativeModules } from 'react-native';

const { MyLibrary } = NativeModules;

export default MyLibrary;
```

**react-native-my-library/ExampleNative/package.json**

```
{
  "name": "ExampleNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-my-library": "file.."
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

## Reproducible demo

Follow the instruction on link: https://reactnative.dev/docs/native-modules-setup

**Comment by lucasbento** [comment]
Hi @dbasilioesp, this is not the correct place to ask about this, I recommend that you try asking this question on https;//stackoverflow.com where you will have much better chances to get a reply.
