### ISSUE TITLE
0.62 /node_modules/react-native/react.gradle' as it does not exist.

### ISSUE THREAD

**Issue by DLevai94** [react-native-community/upgrade-support#18]
## Environment

```System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.67 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found```

## Upgrading version

0.62

## Description

Trying to run android gets this error:

```
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/davidlevai/Work/Classy/Unipie/UnipieApp/android/settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'UnipieApp'.
> Could not read script '/Users/davidlevai/Work/Classy/Unipie/node_modules/react-native/react.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at makeError (/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/execa/index.js:174:9)
    at /Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
```

**Comment by lucasbento** [comment]
What does `/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/react-native/react.gradle` look like?
