### ISSUE TITLE
Migrating from 0.64.2 to 0.67.4 is throwing `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

### ISSUE THREAD

**Issue by pgudivadaDiligent** [react-native-community/upgrade-support#196]
## Environment

info Fetching system and libraries information...
(node:9794) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 29.61 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.0 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:

## Things I’ve done to figure out my issue

- [ x] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.
I also used cli command `npx react-native upgrade 0.67.4` to upgrade

## Upgrading version

0.67.4

## Description

I am getting the following exception whether I use command line/manual upgrade.  

<--- Last few GCs --->

[2048:0x7f94d0008000]  1172230 ms: Mark-sweep 32234.8 (32806.7) -> 32227.6 (32814.7) MB, 4404.1 / 0.0 ms  (average mu = 0.367, current mu = 0.044) allocation failure scavenge might not succeed
[2048:0x7f94d0008000]  1185894 ms: Mark-sweep 32243.8 (32815.2) -> 32235.3 (32822.2) MB, 13615.1 / 0.0 ms  (average mu = 0.168, current mu = 0.004) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10f337a25 node::Abort() (.cold.1) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 2: 0x10e02d0f9 node::Abort() [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 3: 0x10e02d26f node::OnFatalError(char const*, char const*) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 4: 0x10e1ae7e7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 5: 0x10e1ae783 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 6: 0x10e34fe65 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 7: 0x10e34e7ec v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 8: 0x10e35b090 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
 9: 0x10e35b111 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
10: 0x10e3281a7 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
11: 0x10e6dfdae v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
12: 0x10ea89879 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
13: 0x10ea9f102 Builtins_ArrayPrototypeJoin [/Users/user1-local/.nvm/versions/node/v16.14.2/bin/node]
error Command failed: yarn add react-native@0.67.4 react@17.0.2
Error: Command failed: yarn add react-native@0.67.4 react@17.0.2
    at makeError (/Users/user1-local/installDir/node_modules/execa/index.js:174:9)
    at /Users/user1-local/installDir/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDeps (/Users/user1-local/installDir/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:208:3)
    at async Object.upgrade [as func] (/Users/user1-local/installDir/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:346:9)
    at async Command.handleAction (/Users/user1-local/installDir/node_modules/@react-native-community/cli/build/index.js:186:9)

**Comment by glacjay** [comment]
Solved by this: https://github.com/facebook/react-native/issues/32027#issuecomment-900939114

**Comment by lucksp** [comment]
i too had this issue upgrading to SDK47.  I was only able to fix by deleting my yarn lock & reinstalling.  not a good solution
